sudo: required

language: minimal

services:
  - docker

before_install:
  - docker build -t infra-anoop/docker-react-fe5 -f Dockerfile .
  - docker run infra-anoop/docker-react-fe5 npm run test -- --coverage

scripts:
  - docker run infra-anoop/docker-react-fe5 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Anoop-Reactapp"
  environment: "AnoopReactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-074724716397"
  bucket_path: "Anoop-Reactapp"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

on:
  branch: master
