sudo: required

language: minimal

services:
  - docker

install: true

before_script:
  - docker build -t infra-anoop/docker-react-fe5 -f Dockerfile.dev .
  - docker run infra-anoop/docker-react-fe5 npm run test -- --coverage

script:
  - docker build -t infra-anoop/anoop-reactapp -f Dockerfile .

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "anoopreactapp"
  env: "Anoopreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-074724716397"
  bucket_path: "Anoopreactapp"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

on:
  branch: master
