sudo: required

language: minimal

services:
  - docker

before_install:
  - docker build -t infra-anoop/docker-react-fe5 -f Dockerfile.dev .

Install:
  - true

scripts:
  - docker run infra-anoop/docker-react-fe5 npm run test -- --coverage

  
